Numerics: BigInt Header
uhmanoa-transpiler-project/shaka-scheme pull request #60
Opened 2018-03-07 23:40 UTC by 1010jms

Created a header file for the BigInteger class that contains the definitions for the constructors as well as the getter, the conversion functions to Rational and Real, the basic arithmetic operators, and the comparison operators.

Created the initial cpp file that contains comments explaining which algorithms need to be implemented for each function (as well as a link to each algorithm) as well as which functions need to be tested and which functions still need to be figured out.

Created unit test file that successfully tests the BigInteger constructors.

2018-03-08 02:26 UTC, btwooton commented on src/shaka_scheme/system/base/BigInteger.cpp
> +    BigInteger::operator Rational() {
@1010jsm One potential issue with a direct conversion from a `BigInteger` to a `Rational` is that class `Rational` is implemented using `int` to encode the numerator and denominator. Since a `BigInteger` is conceptually converted to a `Rational` by giving its value as the numerator, and 1 as the denominator, this encoding will break down for a direct conversion from `BigInteger` to `Rational`, since the C++ `int` type wont be able to store the `BigInteger` value. Your heart is certainly in the right place, but this is an implementation detail that you will need to consider later. One, potentially naive, option to consider is to have a `BigRational` class that you can seamlessly convert to and from. The numerator and denominator of a `BigRational` would themselves be `BigInteger`s. Just wanted to chime in with that, but I like what I see so far as far as scaffolding goes.

2018-03-08 03:00 UTC, CinchBlue requested changes
Can you split the function bodies into their own `.cpp` file?

2018-03-09 21:31 UTC, Havik2 approved these changes
The header file and test look good to my untrained eye

2018-03-10 01:49 UTC, 1010jms commented
Update: 
- Moved all of the function bodies in the header file to the cpp file, which is currently under construction
- Added more comments for the constructors, arithmetic operators, and comparison operators
- Removed the cpp and unit-test file from this pull request. Will create dedicated pull requests for each file in the future.

2018-03-15 03:03 UTC, CinchBlue approved these changes

2018-03-15 03:15 UTC, merged